# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: csv-xlsx-converter 0.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "csv-xlsx-converter"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["if1live"]
  s.date = "2015-01-13"
  s.description = "Convert CSV to Excel xlsx, Excel xlsx to CSV."
  s.email = "libsora25@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "data/sample-1.csv",
    "lib/csv_xlsx_converter.rb",
    "lib/csv_xlsx_converter/cli.rb",
    "lib/csv_xlsx_converter/converter.rb",
    "lib/csv_xlsx_converter/filename.rb",
    "spec/lib/csv_xlsx_converter/cli_spec.rb",
    "spec/lib/csv_xlsx_converter/converter_spec.rb",
    "spec/lib/csv_xlsx_converter/filename_spec.rb"
  ]
  s.homepage = "http://github.com/if1live/csv-xlsx-converter"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Convert CSV to Excel xlsx, Excel xlsx to CSV."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rubyXL>, [">= 3.3.2"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<rspec>, ["~> 2.13"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
    else
      s.add_dependency(%q<rubyXL>, [">= 3.3.2"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<rspec>, ["~> 2.13"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
    end
  else
    s.add_dependency(%q<rubyXL>, [">= 3.3.2"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<rspec>, ["~> 2.13"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
  end
end

